name: Build and Deploy to Live Environment

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - '.github/**'
  workflow_dispatch:

jobs:
  #######
  #   Clean up old Artifacts
  #######
  cleanup:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '1 hour'

  #######
  #   Build the Artifact
  #     TODO: Add Testing to this process
  #######
  build:
    needs: cleanup
    runs-on: ubuntu-latest
    container: node:16.13.2-alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build
      - name: Upload Next build
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: |
            .next
            public
          retention-days: 1

  #######
  #   Publish to Private Docker Registry
  #######
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download next build
        uses: actions/download-artifact@v2
        with:
          name: build
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and Push Docker Images
        run: |
          export CURRENT_BRANCH=${GITHUB_REF#refs/heads/}
          export TAG=$([[ $CURRENT_BRANCH == "main" ]] && echo "latest" || echo $CURRENT_BRANCH)
          export GITHUB_REF_IMAGE=${{ secrets.REGISTRY_URL }}/seanstoves_web_frontend:$GITHUB_SHA
          export GITHUB_BRANCH_IMAGE=${{ secrets.REGISTRY_URL }}/seanstoves_web_frontend:$TAG
          docker build -t seanstoves_web_frontend -t $GITHUB_REF_IMAGE -t $GITHUB_BRANCH_IMAGE .
          echo "Pushing Image to Chaotic Logic Container Registry"
          docker push $GITHUB_BRANCH_IMAGE
      - name: Redeploy Container
        uses: newarifrh/portainer-service-webhook@v1
        with:
          webhook_url: ${{ secrets.PORTAINER_WEBHOOK }}
